# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed8bf7fe42275fe3634848d16f9a7a17f714b184168dc5d1fb8b10c375647318127e89f1325a675b3d5dca9124c5ddfcc80754df93741c94a53497fa47b841c

test:
  secret_key_base: c8fc28266e3acf098e41ec6b7e57ec75651213c0cef255773dd3105f704265422acdf63e62cd4f249eefa78b12cc160ec618ff4104314712681e382910826423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
